// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOnvS2stfITKL2xKLdAoXO2MHs9vnBtt0',
    appId: '1:1007581634713:web:bc7e4b8663e96d5d9d1808',
    messagingSenderId: '1007581634713',
    projectId: 'hr-performance-analytics',
    authDomain: 'hr-performance-analytics.firebaseapp.com',
    storageBucket: 'hr-performance-analytics.firebasestorage.app',
    measurementId: 'G-6SVZ5X881K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFlb5M79VaqQPQVyLOCeh2N-m6IkOSILI',
    appId: '1:1007581634713:android:5a08afd6c05703449d1808',
    messagingSenderId: '1007581634713',
    projectId: 'hr-performance-analytics',
    storageBucket: 'hr-performance-analytics.firebasestorage.app',
  );
}
